# Generated by Django 3.0.5 on 2020-05-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20200419_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_rating',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
