# Generated by Django 3.0.5 on 2020-05-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_article_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_rating',
            field=models.IntegerField(default=0, verbose_name='рейтинг статьи'),
        ),
    ]
