# Generated by Django 3.0.5 on 2020-06-07 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20200519_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_tags',
            field=models.CharField(default=None, max_length=100, verbose_name='тэги статьи'),
        ),
        migrations.AddField(
            model_name='article',
            name='no_public',
            field=models.BooleanField(default=True),
        ),
    ]
