# Generated by Django 3.0.5 on 2020-06-07 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20200607_0758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_tags',
        ),
    ]
