# Generated by Django 3.0.5 on 2020-06-07 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_remove_article_article_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='no_public',
        ),
    ]
