# Generated by Django 3.0.5 on 2020-06-07 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_remove_article_no_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='no_public',
            field=models.BooleanField(default=True),
        ),
    ]
