# Generated by Django 3.0.5 on 2020-06-07 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_article_no_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_tegs',
            field=models.BooleanField(default=True),
        ),
    ]
