# Generated by Django 3.0.5 on 2020-06-07 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_article_article_tegs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_tegs',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
