# Generated by Django 3.0.5 on 2020-06-07 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_auto_20200607_0903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article_tegs',
            new_name='article_tags',
        ),
    ]
